export const TEXTS_FR = [
  'La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.',
  "L'amitié double les joies et réduit de moitié les peines.",
  "Le sourire est le miroir de l'âme.",
  'La persévérance est la clé du succès.',
  "Le bonheur est parfois caché dans l'inconnu.",
  "Savoir écouter, c'est posséder, outre le sien, le cerveau des autres.",
  'La patience est amère, mais ses fruits sont doux.',
  "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.",
  "Rien n'est impossible, seules les limites de nos esprits définissent certaines choses comme inconcevables.",
  'Le véritable voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.',
  "Il n'y a pas de vent favorable pour celui qui ne sait pas où il va.",
  "Le secret du bonheur, c'est la liberté. Le secret de la liberté, c'est le courage.",
  "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez.",
  "La seule façon de faire du bon travail est d'aimer ce que vous faites.",
  "La vie est faite de petits bonheurs qu'il faut savoir apprécier.",
  'Soyez le changement que vous voulez voir dans le monde.',
  'Chaque instant de vie est un pas vers la mort, et chaque mort est un pas vers la vie éternelle.',
  "Il vaut mieux allumer une bougie que maudire l'obscurité.",
  "La liberté, c'est l'indépendance de la pensée.",
  'La plus perdue de toutes les journées est celle où l’on n’a pas ri.',
  "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.",
  "Le succès c'est d'aller d'échec en échec sans perdre son enthousiasme.",
  'Le seul vrai langage au monde est un baiser.',
  'La musique donne une âme à nos cœurs et des ailes à la pensée.',
  "Le bonheur n'est pas une destination, mais une façon de voyager.",
  "La vraie sagesse est de savoir qu'on ne sait rien.",
  "La vie n'est pas d'attendre que l'orage passe, c'est d'apprendre à danser sous la pluie.",
  'Soyez le héros de votre propre histoire.',
  "Le bonheur, c'est lorsque vos actes sont en accord avec vos paroles.",
  "Il n'y a pas de limites à ce que vous pouvez accomplir, sauf celles que vous vous imposez.",
  "Le plus grand voyageur n'est pas celui qui a fait dix fois le tour du monde, mais celui qui a fait une seule fois le tour de lui-même.",
  'La vie est une aventure audacieuse ou rien du tout.',
  "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.",
  'Les plus belles choses de ce monde ne peuvent être vues ou même touchées. Elles doivent être ressenties avec le cœur.',
  'La vie est comme un arc-en-ciel. Il faut de la pluie et du soleil pour en voir les couleurs.',
  "Si vous voulez connaître quelqu'un, n'écoutez pas ce qu'il dit, mais regardez ce qu'il fait.",
  "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre.",
  'La véritable grandeur réside dans la bonté du cœur.',
  'Le plus grand pouvoir est de pouvoir choisir sa propre vie.',
  'Soyez le changement que vous voulez voir dans le monde.',
  "Le plus grand voyageur n'est pas celui qui a fait dix fois le tour du monde, mais celui qui a fait une seule fois le tour de lui-même.",
  'La vie est une aventure audacieuse ou rien du tout.',
  "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.",
  'Les plus belles choses de ce monde ne peuvent être vues ou même touchées. Elles doivent être ressenties avec le cœur.',
  'La vie est comme un arc-en-ciel. Il faut de la pluie et du soleil pour en voir les couleurs.',
  "Si vous voulez connaître quelqu'un, n'écoutez pas ce qu'il dit, mais regardez ce qu'il fait.",
  "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre.",
  'La véritable grandeur réside dans la bonté du cœur.',
  'Le plus grand pouvoir est de pouvoir choisir sa propre vie.',
  'La seule vraie sagesse est de savoir que vous ne savez rien. Socrate',
  "La vie n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie. Sénèque",
  "Le bonheur est parfois caché dans l'inconnu. Victor Hugo",
  'Soyez le changement que vous voulez voir dans le monde. Gandhi',
  "Rien ne développe l'intelligence comme les voyages. Émile Zola",
  'Ce que nous pensons, ou ce que nous croyons, n’a finalement que peu d’importance. L’essentiel, c’est ce que nous faisons. Éric Emmanuel Schmitt',
  'La folie, c’est se comporter de la même manière et s’attendre à un résultat différent. Albert Einstein',
  "Il faut toujours un chaos en soi pour accoucher d'une étoile qui danse. Friedrich Nietzsche",
  "Le bonheur n'est pas une destination, mais une façon de voyager. Margaret Lee Runbeck",
  'La vie est faite de petits bonheurs. Anonyme',
  "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre. Albert Einstein",
  'Lorsque vous faites quelque chose, vous devez le faire avec votre âme entière. Shunryu Suzuki',
  'La seule chose à craindre, c’est la peur elle-même. Franklin D. Roosevelt',
  'Le bonheur est souvent la seule chose qu’on puisse donner sans l’avoir et c’est en le donnant qu’on l’acquiert. Voltaire',
  'Ce n’est pas ce qui nous arrive qui compte, mais notre attitude envers ce qui nous arrive. Karen Ravn',
  'Il n’y a pas de vent favorable pour celui qui ne sait pas où il va. Sénèque',
  'Soyez le changement que vous voulez voir dans le monde. Gandhi',
  'Ne jugez pas chaque jour sur ce que vous récoltez, mais sur les graines que vous semez. Robert Louis Stevenson',
  "La vie ce n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie. Sénèque",
  "On ne voit bien qu'avec le coeur. L'essentiel est invisible pour les yeux. Antoine de Saint-Exupéry",
  'Il faut viser la lune, parce qu’au moins, si vous échouez, vous finirez dans les étoiles. Oscar Wilde',
  'La vraie sagesse de la vie consiste à voir l’extraordinaire dans l’ordinaire. Pearl Buck',
  'Si vous voulez vivre une vie heureuse, attachez-la à un but, non pas à des personnes ou des choses. Albert Einstein',
  'Chaque jour est une nouvelle chance de changer votre vie. Anonyme',
  'Le bonheur est un papillon qui, lorsqu’il est poursuivi, est toujours juste hors de votre portée, mais qui, si vous vous asseyez tranquillement, peut se poser sur vous. Nathaniel Hawthorne',
  "La vie est un mystère qu'il faut vivre et non un problème à résoudre. Gandhi",
  "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. Eleanor Roosevelt",
  "Le bonheur n'est pas quelque chose que l'on possède, il est quelque chose que l'on est. Anonyme",
  "Ne confonds pas ton chemin avec ta destination. Ce n'est pas parce que le temps est orageux aujourd'hui que cela signifie que tu n'es pas en train de te diriger vers le soleil. Anonyme",
  'La vie est trop courte pour être petite. Benjamin Disraeli',
  'Chaque instant de notre vie est un pas vers lequel nous nous dirigeons. Anonyme',
  "N'abandonnez jamais votre droit de rêver. Dalton Trumbo",
  'La réussite, c’est d’être capable d’aller d’échec en échec sans perdre son enthousiasme. Winston Churchill',
  'La vie est faite de rencontres, de séparations et de retrouvailles. Anonyme',
  'Dans la vie, il n’y a pas de problèmes, il n’y a que des solutions. John Lennon',
  'On ne peut apprendre la sagesse qu’à la suite d’un échec. Confucius',
  'Ne perdez pas votre temps à essayer de plaire à tout le monde. Anonyme',
  "La vie n'est pas d'attendre que l'orage passe, mais d'apprendre à danser sous la pluie. Sénèque",
  'Même le plus long des voyages commence par un simple pas. Lao Tseu',
  "La sagesse, c'est d'avoir des rêves suffisamment grands pour ne pas les perdre de vue lorsqu'on les poursuit. Oscar Wilde",
  "Si vous avez l'impression que vous êtes trop petit pour changer quelque chose, essayez donc de dormir avec un moustique et vous verrez lequel des deux empêche l'autre de dormir. Dala Lama",
  'La sagesse commence dans l’émerveillement. Socrate',
  "Il n'y a pas de génie sans un grain de folie. Aristote",
  "La vie est un mystère qu'il faut vivre et non un problème à résoudre. Gandhi",
  'Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. Albert Schweitzer',
  'Ce n’est pas ce que nous avons, mais ce que nous sommes, qui constitue notre abondance. Epicure',
  'Le plus grand risque est de ne prendre aucun risque. Dans un monde qui évolue rapidement, la seule stratégie qui est sûre d’échouer est de ne prendre aucun risque. Mark Zuckerberg',
  'Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. Albert Schweitzer',
  'Ce n’est pas ce que nous avons, mais ce que nous sommes, qui constitue notre abondance. Epicure',
  "Il faut toujours un chaos en soi pour accoucher d'une étoile qui danse. Friedrich Nietzsche",
  "Le bonheur n'est pas une destination, mais une façon de voyager. Margaret Lee Runbeck",
  'La vie est faite de petits bonheurs. Anonyme',
  "L'important n'est pas de convaincre, mais de donner à réfléchir. Bernard Werber",
  'Là où il y a une volonté, il y a un chemin. Alexandre Dumas',
  "La vraie générosité envers l'avenir consiste à tout donner au présent. Albert Camus",
  'Le courage, c’est de comprendre sa propre vie. Le courage, c’est d’aimer la vie et de regarder la mort d’un regard tranquille. Jules Michelet',
  "La beauté commence au moment où vous décidez d'être vous-même. Coco Chanel",
  "La vie est un mystère qu'il faut vivre et non un problème à résoudre. Gandhi",
  "Rien n'est permanent, sauf le changement. Bouddha",
  'Le seul vrai langage au monde est un baiser. Alfred de Musset',
  'La musique est la langue des émotions. Emmanuel Kant',
  "On ne voit bien qu'avec le coeur. L'essentiel est invisible pour les yeux. Antoine de Saint-Exupéry",
  "Le bonheur est parfois caché dans l'inconnu. Victor Hugo",
  "Il y a des moments où il faut choisir entre vivre sa propre vie pleinement, entièrement, complètement, ou traîner l'existence dégradante, creuse et fausse que le monde, dans sa stupidité, nous impose. Oscar Wilde",
  'La seule façon d’être vraiment satisfait est de faire ce que vous croyez être un excellent travail. Steve Jobs',
  'La connaissance parle, mais la sagesse écoute. Jimi Hendrix',
  "On n'est jamais mieux servi que par soi-même. Proverbe français",
  'La confiance en soi est le premier secret du succès. Ralph Waldo Emerson',
  "Le pessimiste se plaint du vent, l'optimiste espère qu'il va changer, le réaliste ajuste ses voiles. William Arthur Ward",
  "La perfection n'est pas atteinte lorsque vous ne pouvez plus rien ajouter, mais lorsque vous ne pouvez plus rien retirer. Antoine de Saint-Exupéry",
  "La créativité est l'intelligence qui s'amuse. Albert Einstein",
  'La véritable éducation consiste à tirer le meilleur de soi-même. Mahatma Gandhi',
  'La patience est amère, mais son fruit est doux. Jean-Jacques Rousseau',
  "L'optimisme est la foi qui mène à la réalisation. Rien ne peut être fait sans espoir et confiance. Helen Keller",
  'La simplicité est la sophistication suprême. Léonard de Vinci',
  'La patience est la clé du soulagement.',
  'Celui qui veut bien vivre doit agir sagement.',
  'La patience est un arbre dont la racine est amère, mais dont les fruits sont doux.',
  'Si tu veux être respecté, respecte-toi toi-même.',
  'La peur d’un danger est souvent plus terrible que le danger lui-même.',
  'Le diable est sage, mais pas autant qu’un homme de bien.',
  'Le chameau ne voit pas sa propre bosse, mais voit celle des autres.',
  "Même la lune ne brille pas autant que l'humilité.",
  'La fortune sourit à celui qui travaille dur.',
  "L'intelligence s'acquiert dans la sérénité et le silence.",
  'Il n’y a pas de honte à apprendre, même auprès de son ennemi.',
  "Celui qui a beaucoup parlé a beaucoup commis d'erreurs.",
  'Le silence est la meilleure réponse à un imbécile.',
  'Un homme n’est pas bon ou mauvais à cause des richesses qu’il possède, mais par ses actes.',
  'Le bienfait du coeur est une source inépuisable de richesse.',
  'Un moment de patience dans un moment de colère évite un siècle de chagrin.',
  "Il vaut mieux une goutte de sagesse qu'un tonneau de science.",
  'La gentillesse est un langage que les sourds peuvent entendre et que les aveugles peuvent voir.',
  'Celui qui se respecte lui-même est respecté par les autres.',
  'Un homme sans patience est comme une lampe sans huile.',
  'Le calme est une force intérieure.',
  'Ton amour est comme un doux rêve qui embellit ma réalité chaque jour. Chaque moment passé à tes côtés est une symphonie où mon cœur bat en harmonie avec le tien.',
  "Dans ton regard, je trouve la force de conquérir les montagnes les plus hautes et la tendresse pour apaiser les tempêtes les plus violentes. Ton amour est mon phare dans l'océan de la vie.",
  'Chaque sourire sur ton visage est une étoile dans mon ciel, illuminant mes jours les plus sombres. Ton amour est mon refuge, où je trouve paix et sérénité, dans un monde parfois chaotique.',
  'Nos rires résonnent en harmonie, comme une douce mélodie qui berce nos cœurs. Chaque moment partagé avec toi est une aventure passionnante, un voyage où je découvre encore et encore la beauté de ton âme.',
  "Ton amour est un poème éternel écrit dans mon cœur, une histoire sans fin où chaque chapitre est plus merveilleux que le précédent. Avec toi, chaque jour est une promesse de bonheur et d'amour infini.",
  'Dans tes yeux, je trouve une symphonie de couleurs où se mêlent la passion, la douceur et la tendresse. Chaque battement de mon cœur chante le refrain de notre amour éternel.',
  'Chaque éclat de ton rire est une note de bonheur dans la partition de ma vie. Ton amour est un jardin secret où fleurissent les plus belles émotions, un trésor précieux qui illumine mes jours.',
  "Avec toi, chaque instant devient une œuvre d'art, chaque regard échangé une poésie silencieuse. Ton amour est la toile sur laquelle se dessine la beauté de notre histoire.",
  "Ton sourire est mon phare dans les nuits les plus sombres, une lumière qui guide mes pas vers le bonheur. Ton amour est une danse gracieuse, un ballet où nos cœurs s'unissent en parfaite harmonie.",
  'Dans chaque étreinte, je trouve la chaleur de mille soleils, la tendresse qui apaise les tourments. Ton amour est le plus beau chapitre de mon histoire, une aventure inoubliable où chaque moment est précieux.',
  "Chaque battement de mon cœur murmure ton nom, chaque souffle chante l'hymne de notre amour. Ton amour est une symphonie magique qui enivre mon âme et embellit ma vie.",
  'Ta voix est la mélodie qui berce mes nuits, le réconfort qui apaise mes peurs. Ton amour est mon refuge, mon havre de paix où je me sens en sécurité, entouré(e) de ton affection.',
  "Avec toi, chaque journée est un chapitre de bonheur, un poème qui s'écrit à chaque sourire échangé. Ton amour est ma muse, l'inspiration qui donne vie à mes rêves les plus doux.",
  'Dans chaque regard échangé, je trouve la complicité et la tendresse qui font vibrer nos âmes. Ton amour est un trésor précieux, un joyau qui illumine ma vie.',
  "Ton amour est comme une pluie de pétales de roses, douce et délicate, qui égaye mes journées. Chaque instant passé avec toi est un cadeau précieux, une perle rare dans l'océan du temps.",
  "Avec toi, je trouve la force d'affronter les tempêtes et la douceur pour apaiser les tourments. Ton amour est un refuge où je me sens en sécurité, entouré(e) de tendresse et de bienveillance.",
  'Chaque mot tendre que tu murmures est une caresse pour mon cœur, une douceur qui enveloppe mon âme. Ton amour est ma boussole, mon guide dans les méandres de la vie.',
  "Dans chaque éclat de rire partagé, je trouve la magie et la complicité qui rendent notre histoire si unique. Ton amour est ma source d'inspiration, une énergie qui alimente mes rêves les plus fous.",
  "Avec toi, chaque pas est une danse, chaque instant une célébration de l'amour. Ton amour est un trésor inestimable, une richesse qui donne un sens à ma vie.",
  'Chaque regard échangé est un dialogue silencieux où nos âmes se comprennent sans mots. Ton amour est une étoile dans ma nuit, un rayon de lumière qui éclaire mon chemin.',
  'Ton amour est la plus belle des mélodies dans le concert de ma vie.',
  "Chaque regard échangé est une promesse d'amour et de tendresse.",
  'Ta présence est un cadeau précieux que je chéris chaque jour.',
  'Dans tes bras, je trouve la paix et la sécurité que je recherche.',
  'Ton sourire illumine mes journées les plus sombres, apportant la lumière à mon univers.',
  'Avec toi, chaque moment est une aventure où nos cœurs dansent en harmonie.',
  'Chaque mot tendre que tu murmures est une caresse à mon âme.',
  'Ton amour est mon refuge dans un monde parfois chaotique.',
  'Dans ton regard, je trouve la pureté et la sincérité de ton amour.',
  'Chaque étreinte est une déclaration silencieuse de notre connexion profonde.',
];

export const TEXTS_EN = [
  'Your love is the most beautiful melody in the concert of my life.',
  'Every exchanged glance is a promise of love and tenderness.',
  'Your presence is a precious gift that I cherish every day.',
  'In your arms, I find the peace and security I seek.',
  'Your smile brightens my darkest days, bringing light to my world.',
  'With you, every moment is an adventure where our hearts dance in harmony.',
  'Every tender word you whisper is a caress to my soul.',
  'Your love is my refuge in a sometimes chaotic world.',
  'In your gaze, I find the purity and sincerity of your love.',
  'Every embrace is a silent declaration of our deep connection.',
  'Your love is like a sweet dream that embellishes my reality every day. Every moment spent with you is a symphony where my heart beats in harmony with yours.',
  'In your eyes, I find the strength to conquer the highest mountains and the tenderness to calm the fiercest storms. Your love is my lighthouse in the ocean of life.',
  'Every smile on your face is a star in my sky, illuminating my darkest days. Your love is my refuge, where I find peace and serenity in a sometimes chaotic world.',
  'Our laughter resonates in harmony, like a sweet melody that lulls our hearts. Every moment shared with you is an exciting adventure, a journey where I discover the beauty of your soul over and over again.',
  'Your love is an eternal poem written in my heart, an endless story where each chapter is more wonderful than the last. With you, every day is a promise of infinite happiness and love.',
  'In your eyes, I find a symphony of colors where passion, gentleness, and tenderness intertwine. Every beat of my heart sings the refrain of our eternal love.',
  'Every sparkle of your laughter is a note of happiness in the score of my life. Your love is a secret garden where the most beautiful emotions flourish, a precious treasure that brightens my days.',
  'With you, every moment becomes a work of art, every exchanged glance a silent poetry. Your love is the canvas on which the beauty of our story unfolds.',
  'Your smile is my lighthouse in the darkest nights, a light that guides my steps towards happiness. Your love is a graceful dance, a ballet where our hearts unite in perfect harmony.',
  'In each embrace, I find the warmth of a thousand suns, the tenderness that soothes the storms. Your love is the most beautiful chapter of my story, an unforgettable adventure where every moment is precious.',
  'Every beat of my heart whispers your name, every breath sings the hymn of our love. Your love is a magical symphony that intoxicates my soul and embellishes my life.',
  'Your voice is the melody that lulls my nights, the comfort that soothes my fears. Your love is my refuge, my haven of peace where I feel safe, surrounded by your affection.',
  'With you, each day is a chapter of happiness, a poem written with every exchanged smile. Your love is my muse, the inspiration that brings my sweetest dreams to life.',
  'In each exchanged glance, I find the complicity and tenderness that resonate within our souls. Your love is a precious treasure, a jewel that brightens my life.',
  'Your love is like a rain of rose petals, gentle and delicate, that brightens my days. Every moment spent with you is a precious gift, a rare pearl in the ocean of time.',
  'With you, I find the strength to face storms and the tenderness to soothe turmoil. Your love is a refuge where I feel safe, surrounded by tenderness and kindness.',
  "Every tender word you whisper is a caress to my heart, a sweetness that envelops my soul. Your love is my compass, my guide through life's twists and turns.",
  'In every shared burst of laughter, I find the magic and complicity that make our story so unique. Your love is my source of inspiration, an energy that fuels my wildest dreams.',
  'With you, every step is a dance, every moment a celebration of love. Your love is an invaluable treasure, a richness that gives meaning to my life.',
  'Every exchanged glance is a silent dialogue where our souls understand each other without words. Your love is a star in my night, a ray of light that illuminates my path.',
  'The only true wisdom is in knowing you know nothing. Socrates',
  'Life is not about waiting for the storms to pass, it’s about learning to dance in the rain. Seneca',
  'Happiness is sometimes hidden in the unknown. Victor Hugo',
  'Be the change that you want to see in the world. Gandhi',
  'Nothing develops intelligence like travel. Émile Zola',
  'What we think, or what we believe, ultimately, has little importance. The essential thing is what we do. Éric Emmanuel Schmitt',
  'Insanity is doing the same thing over and over again and expecting a different result. Albert Einstein',
  'There must always be a chaos within oneself to give birth to a dancing star. Friedrich Nietzsche',
  'Happiness is not a destination, but a way of traveling. Margaret Lee Runbeck',
  'Life is made of small joys. Anonymous',
  'Life is like riding a bicycle, to keep your balance, you must keep moving. Albert Einstein',
  'When you do something, you must do it with your whole soul. Shunryu Suzuki',
  'The only thing we have to fear is fear itself. Franklin D. Roosevelt',
  'Happiness is often the only thing we can give without having it, and it’s by giving it that we acquire it. Voltaire',
  'It’s not what happens to us that matters, but our attitude toward what happens to us. Karen Ravn',
  'There is no favorable wind for the one who does not know where they are going. Seneca',
  'Be the change that you want to see in the world. Gandhi',
  'Do not judge each day by what you harvest, but by the seeds that you sow. Robert Louis Stevenson',
  'Life is not about waiting for the storms to pass, it’s about learning to dance in the rain. Seneca',
  'We see clearly only with the heart. The essential is invisible to the eyes. Antoine de Saint-Exupéry',
  'Aim for the moon, because even if you miss, you’ll land among the stars. Oscar Wilde',
  'The true wisdom of life is to see the extraordinary in the ordinary. Pearl Buck',
  'If you want to live a happy life, tie it to a goal, not to people or things. Albert Einstein',
  'Every day is a new chance to change your life. Anonymous',
  'Happiness is like a butterfly; the more you chase it, the more it will elude you, but if you turn your attention to other things, it will come and sit softly on your shoulder. Nathaniel Hawthorne',
  'Life is a mystery to be lived, not a problem to be solved. Gandhi',
  'The future belongs to those who believe in the beauty of their dreams. Eleanor Roosevelt',
  'Happiness is not something you possess; it is something you are. Anonymous',
  'Do not confuse your path with your destination. Just because it’s stormy now doesn’t mean you aren’t headed for sunshine. Anonymous',
  'Life is too short to be small. Benjamin Disraeli',
  'Even the longest journey begins with a single step. Lao Tzu',
  'Wisdom is having dreams big enough not to lose sight of them when pursuing them. Oscar Wilde',
  'If you feel you’re too small to make a difference, try sleeping with a mosquito. Dalai Lama',
  'Wisdom begins in wonder. Socrates',
  'There is no genius without a touch of madness. Aristotle',
  'Life is a mystery to be lived, not a problem to be solved. Gandhi',
  'Happiness is the key to success. If you love what you are doing, you will be successful. Albert Schweitzer',
  'It’s not what we have but who we are that constitutes our abundance. Epicure',
  'The greatest risk is to take no risk at all. In a world that is changing quickly, the only strategy that is sure to fail is not taking any risks. Mark Zuckerberg',
  'Success is not the key to happiness. Happiness is the key to success. If you love what you do, you will succeed. Albert Schweitzer',
  'It’s not what we have but who we are that constitutes our abundance. Epicure',
  'There must always be chaos within oneself to give birth to a dancing star. Friedrich Nietzsche',
  'Happiness is not a destination, but a way of traveling. Margaret Lee Runbeck',
  'Life is made of small joys. Anonymous',
  'The important thing is not to convince, but to make people think. Bernard Werber',
  'Where there is a will, there is a way. Alexandre Dumas',
  'True generosity toward the future lies in giving all to the present. Albert Camus',
  'Courage is to understand one’s own life. Courage is to love life and to look at death with a calm gaze. Jules Michelet',
  'Beauty begins the moment you decide to be yourself. Coco Chanel',
  'Life is a mystery to be lived, not a problem to be solved. Gandhi',
  'Nothing is permanent except change. Buddha',
  'The only true language in the world is a kiss. Alfred de Musset',
  'Music is the language of emotions. Immanuel Kant',
  'We see clearly only with the heart. The essential is invisible to the eyes. Antoine de Saint-Exupéry',
  'Happiness is sometimes hidden in the unknown. Victor Hugo',
  "There are moments when one must choose between living one's own life fully, entirely, completely, or dragging the degrading, hollow, and false existence that the world, in its stupidity, imposes on us. Oscar Wilde",
  'The only way to be truly satisfied is to do what you believe is excellent work. Steve Jobs',
  'Knowledge speaks, but wisdom listens. Jimi Hendrix',
  "You're never served better than by yourself. French Proverb",
  'Self-confidence is the first secret of success. Ralph Waldo Emerson',
  'The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails. William Arthur Ward',
  "Perfection is achieved not when you can't add anything more, but when you can't take anything away. Antoine de Saint-Exupéry",
  'Creativity is intelligence having fun. Albert Einstein',
  'True education consists in drawing out the best from yourself. Mahatma Gandhi',
  'Patience is bitter, but its fruit is sweet. Jean-Jacques Rousseau',
  'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. Helen Keller',
  'Simplicity is the ultimate sophistication. Leonardo da Vinci',
  'Patience is the key to relief.',
  'He who wants to live well must act wisely.',
  'Life is a challenge to be met, a happiness to be earned, an adventure to be ventured.',
  'Friendship doubles joys and halves sorrows.',
  'A smile is the mirror of the soul.',
  'Perseverance is the key to success.',
  'Happiness is sometimes hidden in the unknown.',
  "Listening carefully means owning others' minds besides your own.",
  'Patience is bitter, but its fruit is sweet.',
  'The future belongs to those who believe in the beauty of their dreams.',
  "Nothing is impossible; the limits we place on ourselves define what's impossible.",
  'The true voyage of discovery is not in seeking new landscapes but in having new eyes.',
  "There's no favorable wind for the one who doesn't know where they're going.",
  'The secret to happiness is freedom. The secret to freedom is courage.',
  "Success isn't the key to happiness. Happiness is the key to success. If you love what you do, you'll succeed.",
  'The only way to do great work is to love what you do.',
  'Life is filled with small beautiful moments that we must appreciate.',
  'Be the change you want to see in the world.',
  'Every moment in life is a step towards death, and every death is a step towards eternal life.',
  "It's better to light a candle than to curse the darkness.",
  'Freedom is independence of thought.',
  'The most wasted of all days is one without laughter.',
  'Life is like riding a bicycle; to keep your balance, you must keep moving.',
  'Success is going from failure to failure without losing enthusiasm.',
  'The only true language in the world is a kiss.',
  'Music gives a soul to the universe, wings to the mind.',
  'Happiness is not a destination, but a way of travel.',
  'True wisdom is knowing that you know nothing.',
  "Life isn't about waiting for the storm to pass; it's about learning to dance in the rain.",
  'Be the hero of your own story.',
  'Happiness is when your actions are in harmony with your words.',
  'There are no limits to what you can accomplish, except the ones you set for yourself.',
  "The greatest traveler isn't the one who's traveled around the world ten times, but the one who's traveled around themselves once.",
  'Life is a bold adventure or nothing at all.',
  'The future belongs to those who believe in the beauty of their dreams.',
  'The most beautiful things in this world cannot be seen or touched; they must be felt with the heart.',
  'Life is like a rainbow. You need both rain and sun to see its colors.',
  "If you want to know someone, don't listen to what they say, but watch what they do.",
  "Courage isn't the absence of fear, but the ability to overcome it.",
  'True greatness lies in the kindness of the heart.',
  'The greatest power is being able to choose your own life.',
];
export const TEXTS_AR = [
  'الصبر والاجتهاد يصنعان النجاح ويخلقان فرصًا لتحقيق الأحلام والأهداف في الحياة.',
  'التفاؤل هو مفتاح السعادة، فإيماننا بالأشياء الجيدة يجلبها إلينا ويضيء طريقنا في الحياة.',
  'الاحترام والتقدير للآخرين يبني جسورًا من الثقة والتعاون يعزز العلاقات بين الأفراد والمجتمعات.',
  'المرونة في التفكير والتكيف مع التغييرات هي صفات أساسية تساعدنا على التكيف مع التحديات الحياتية.',
  'التواضع والعفوية يجعلان الإنسان أكثر جاذبية ويخلقان جوًا إيجابيًا حوله يؤثر على الآخرين بشكل جيد.',
  'التعلم من الأخطاء هو جزء لا يتجزأ من النمو الشخصي، فمن خلالها نكتسب الخبرة ونصبح أقوى وأفضل.',
  'الأمل والإيمان بالغد يمنحان القوة للواحد ليواجه الصعاب ويستمر في مسيرته نحو النجاح.',
  'المسؤولية عن أفعالنا تصقل شخصيتنا وتجعلنا نمتلك القوة لتحقيق التغيير الإيجابي في العالم من حولنا.',
  'العمل الجماعي وروح الفريق هما أساس النجاح في أي مجال، فالتعاون يحقق الأهداف بفعالية وسرعة أكبر.',
  'العقل المتفتح والقدرة على قبول الآخرين وتقدير التنوع يثري حياتنا ويفتح آفاقًا جديدة للفهم والتطور.',
  'الصديق وقت الضيق هو من يظهر صدق العلاقات ويثبت قيمة الصداقة في الظروف الصعبة.',
  'الحياة مليئة بالتحديات والفشل ليس نهاية الطريق بل درس يعلمنا كيف ننجح في المحاولة القادمة.',
  'العلم هو السلاح الأقوى الذي يفتح أبواب الفهم ويمنح الفرص لبناء مستقبل أفضل للإنسانية.',
  'الإيمان بالذات هو أساس كل نجاح، فعندما يؤمن الإنسان بقدراته يستطيع تحقيق ما يصبو إليه.',
  'العمل الجاد والمثابرة هما السبيل لتحقيق الأهداف وتحويل الأحلام إلى واقع ملموس.',
  'الحقيقة والنزاهة هما عمودان أساسيان في بناء علاقات قوية ومستدامة بين الناس.',
  'السعادة ليست وجهة نصل إليها بل رحلة نعيشها باكتشاف اللحظات الجميلة في حياتنا اليومية.',
  'التعلم المستمر هو مفتاح النجاح والتطور الشخصي الذي يمكننا من مواجهة تحديات الحياة.',
  'الإبداع ينشأ من التفكير المختلف والتجارب المستمرة التي تسمح لنا برؤية العالم بشكل جديد.',
  'الصبر والثبات هما صفتان مهمتان تساعداننا على تحمل الصعاب والوقوف بثبات في وجه التحديات.',
  'العلم نور',
  'الصحة تاج على رؤوس الأصحاء لا يراه إلا المرضى',
  'الأمل آخر الطريق',
  'الأمل خير جليس في الحزن',
  'الجمال جمال الأخلاق',
  'القريب على الدرب',
  'الصديق وقت الضيق',
  'الصبر مفتاح الفرج',
  'العقل زينة الرجل',
  'الوفاء مفتاح القلوب',
  'النية الحسنة تفوق الفعل الحسن',
  'الحب أعمى',
  'العقل زينة الرجل',
  'الأمانة سر العلاقة',
  'الحياة قصيرة فلا تقصرها بأخطاء',
  'الابتسامة صدقة',
  'المال يذهب ويأتي والصحة تذهب ولا تعود',
  'الصديق وقت الضيق',
  'الحب يصنع المعجزات',
  'الصديق وقت الضيق',
  'الصديق وقت الضيق',
  'لا يأس مع الحياة',
  'العزيمة تخلق المعجزات',
  'الحكمة خير ميراث',
  'العقل زينة الرجل',
  'العلم نور',
  'المال يذهب ويأتي والصحة تذهب ولا تعود',
  'الصديق وقت الضيق',
  'العقل زينة الرجل',
  'الأمانة سر العلاقة',
  'الصديق وقت الضيق',
  'الصبر مفتاح الفرج',
  'النية الحسنة تفوق الفعل الحسن',
  'الصديق وقت الضيق',
  'الحب أعمى',
  'العقل زينة الرجل',
  'الأمانة سر العلاقة',
  'الصديق وقت الضيق',
  'الصبر مفتاح الفرج',
  'الحب أعمى',
  'الصديق وقت الضيق',
  'الصديق وقت الضيق',
  'العزيمة تخلق المعجزات',
  'العقل زينة الرجل',
  'العلم نور',
  'الأمانة سر العلاقة',
  'الصديق وقت الضيق',
  'الحب يصنع المعجزات',
  'الحكمة خير ميراث',
  'الصديق وقت الضيق',
  'الحياة تحدٍ يجب التغلب عليه، سعادة يجب أن نستحقها، مغامرة يجب أن نخوضها.',
  'الصداقة تُضاعف الفرح وتقلل الأحزان إلى النصف.',
  'الابتسامة هي مرآة الروح.',
  'المثابرة هي مفتاح النجاح.',
  'السعادة أحيانًا مخفية في المجهول.',
  'الاستماع بعناية يعني امتلاك عقل الآخرين بالإضافة إلى عقلك الخاص.',
  'الصبر مرّ، لكن ثماره حلوة.',
  'المستقبل ينتمي لأولئك الذين يؤمنون بجمال أحلامهم.',
  'لا شيء مستحيل، الحدود التي نضعها في عقولنا هي التي تحدد ما هو مستحيل.',
  'الرحلة الحقيقية للكشف ليست في البحث عن مناظر جديدة، بل في النظر بعيون جديدة.',
  'ليس هناك ريح مواتية لمن لا يعرف إلى أين يتجه.',
  'سر السعادة هو الحرية. سر الحرية هو الشجاعة.',
  'النجاح ليس مفتاح السعادة. السعادة هي مفتاح النجاح. إذا كنت تحب ما تفعل، فستنجح.',
  'الطريقة الوحيدة للقيام بعمل جيد هي أن تحب ما تفعل.',
  'الحياة مليئة بأحداث صغيرة جميلة يجب أن نقدرها.',
  'كن تغييرًا تريد أن تراه في العالم.',
  'كل لحظة في الحياة خطوة نحو الموت، وكل موت خطوة نحو الحياة الأبدية.',
  'من الأفضل أن تشعل شمعة بدلًا من أن تلعن الظلام.',
  'الحرية هي استقلالية الفكر.',
  'أكثر الأيام فقدًا هي تلك التي لم نضحك فيها.',
  'الحياة مثل الدراجة، عليك أن تتحرك لكي لا تفقد توازنك.',
  'النجاح هو الذهاب من فشل إلى فشل دون فقدان الحماس.',
  'اللغة الحقيقية الوحيدة في العالم هي القبلة.',
  'الموسيقى تعطي روحًا لقلوبنا وجناحًا لأفكارنا.',
  'السعادة ليست وجهة، بل هي طريقة للسفر.',
  'الحكمة الحقيقية هي أن نعلم أننا لا نعرف شيئًا.',
  'الحياة ليست في انتظار المطر وحده، بل في معرفة كيف ترقص تحت المطر.',
  'كن بطل حكايتك الخاصة.',
  'السعادة عندما تكون أفعالك متسقة مع كلماتك.',
  'لا حدود لما يمكنك تحقيقه إلا تلك التي تضعها لنفسك.',
  'أكبر مسافر ليس من سافر عشر مرات حول العالم، بل من سافر مرة واحدة حول ذاته.',
  'الحياة مغامرة جريئة أو لا شيء.',
  'المستقبل ينتمي لأولئك الذين يؤمنون بجمال أحلامهم.',
  'أجمل الأشياء في هذا العالم لا يمكن رؤيتها أو لمسها حتى. يجب أن تشعر بها بقلبك.',
  'الحياة مثل قوس قزح. يجب أن تكون هناك مطر وشمس لنرى الألوان.',
  'إذا أردت أن تعرف شخصًا، فلا تستمع لما يقوله، بل انظر ما يفعل.',
  'الشجاعة ليست عدم الخوف، بل القدرة على التغلب عليه.',
  'العظمة الحقيقية تكمن في جودة القلب.',
  'أعظم قوة هي أن تستطيع اختيار حياتك بنفسك.',
];
