export const textes = [
  'La seule vraie sagesse est de savoir que vous ne savez rien. - Socrate',
  "La vie n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie. - Sénèque",
  "Le bonheur est parfois caché dans l'inconnu. - Victor Hugo",
  'Soyez le changement que vous voulez voir dans le monde. - Gandhi',
  "Rien ne développe l'intelligence comme les voyages. - Émile Zola",
  'Ce que nous pensons, ou ce que nous croyons, n’a finalement que peu d’importance. L’essentiel, c’est ce que nous faisons. - Éric Emmanuel Schmitt',
  'La folie, c’est se comporter de la même manière et s’attendre à un résultat différent. - Albert Einstein',
  "Il faut toujours un chaos en soi pour accoucher d'une étoile qui danse. - Friedrich Nietzsche",
  "Le bonheur n'est pas une destination, mais une façon de voyager. - Margaret Lee Runbeck",
  'La vie est faite de petits bonheurs. - Anonyme',
  "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre. - Albert Einstein",
  'Lorsque vous faites quelque chose, vous devez le faire avec votre âme entière. - Shunryu Suzuki',
  'La seule chose à craindre, c’est la peur elle-même. - Franklin D. Roosevelt',
  'Le bonheur est souvent la seule chose qu’on puisse donner sans l’avoir et c’est en le donnant qu’on l’acquiert. - Voltaire',
  'Ce n’est pas ce qui nous arrive qui compte, mais notre attitude envers ce qui nous arrive. - Karen Ravn',
  'Il n’y a pas de vent favorable pour celui qui ne sait pas où il va. - Sénèque',
  'Soyez le changement que vous voulez voir dans le monde. - Gandhi',
  'Ne jugez pas chaque jour sur ce que vous récoltez, mais sur les graines que vous semez. - Robert Louis Stevenson',
  "La vie ce n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie. - Sénèque",
  "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux. - Antoine de Saint-Exupéry",
  'Il faut viser la lune, parce qu’au moins, si vous échouez, vous finirez dans les étoiles. - Oscar Wilde',
  'La vraie sagesse de la vie consiste à voir l’extraordinaire dans l’ordinaire. - Pearl Buck',
  'Si vous voulez vivre une vie heureuse, attachez-la à un but, non pas à des personnes ou des choses. - Albert Einstein',
  'Chaque jour est une nouvelle chance de changer votre vie. - Anonyme',
  'Le bonheur est un papillon qui, lorsqu’il est poursuivi, est toujours juste hors de votre portée, mais qui, si vous vous asseyez tranquillement, peut se poser sur vous. - Nathaniel Hawthorne',
  "La vie est un mystère qu'il faut vivre et non un problème à résoudre. - Gandhi",
  "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. - Eleanor Roosevelt",
  "Le bonheur n'est pas quelque chose que l'on possède, il est quelque chose que l'on est. - Anonyme",
  "Ne confonds pas ton chemin avec ta destination. Ce n'est pas parce que le temps est orageux aujourd'hui que cela signifie que tu n'es pas en train de te diriger vers le soleil. - Anonyme",
  'La vie est trop courte pour être petite. - Benjamin Disraeli',
  'Chaque instant de notre vie est un pas vers lequel nous nous dirigeons. - Anonyme',
  "N'abandonnez jamais votre droit de rêver. - Dalton Trumbo",
  'La réussite, c’est d’être capable d’aller d’échec en échec sans perdre son enthousiasme. - Winston Churchill',
  'La vie est faite de rencontres, de séparations et de retrouvailles. - Anonyme',
  'Dans la vie, il n’y a pas de problèmes, il n’y a que des solutions. - John Lennon',
  'On ne peut apprendre la sagesse qu’à la suite d’un échec. - Confucius',
  'Ne perdez pas votre temps à essayer de plaire à tout le monde. - Anonyme',
  "La vie n'est pas d'attendre que l'orage passe, mais d'apprendre à danser sous la pluie. - Sénèque",
  'Même le plus long des voyages commence par un simple pas. - Lao Tseu',
  "La sagesse, c'est d'avoir des rêves suffisamment grands pour ne pas les perdre de vue lorsqu'on les poursuit. - Oscar Wilde",
  "Si vous avez l'impression que vous êtes trop petit pour changer quelque chose, essayez donc de dormir avec un moustique et vous verrez lequel des deux empêche l'autre de dormir. - Dalaï Lama",
  'La sagesse commence dans l’émerveillement. - Socrate',
  "Il n'y a pas de génie sans un grain de folie. - Aristote",
  "La vie est un mystère qu'il faut vivre et non un problème à résoudre. - Gandhi",
  'Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. - Albert Schweitzer',
  'Ce n’est pas ce que nous avons, mais ce que nous sommes, qui constitue notre abondance. - Epicure',
  'Le plus grand risque est de ne prendre aucun risque. Dans un monde qui évolue rapidement, la seule stratégie qui est sûre d’échouer est de ne prendre aucun risque. - Mark Zuckerberg',
  'Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. - Albert Schweitzer',
  'Ce n’est pas ce que nous avons, mais ce que nous sommes, qui constitue notre abondance. - Epicure',
  "Il faut toujours un chaos en soi pour accoucher d'une étoile qui danse. - Friedrich Nietzsche",
  "Le bonheur n'est pas une destination, mais une façon de voyager. - Margaret Lee Runbeck",
  'La vie est faite de petits bonheurs. - Anonyme',
  "L'important n'est pas de convaincre, mais de donner à réfléchir. - Bernard Werber",
  'Là où il y a une volonté, il y a un chemin. - Alexandre Dumas',
  "La vraie générosité envers l'avenir consiste à tout donner au présent. - Albert Camus",
  'Le courage, c’est de comprendre sa propre vie. Le courage, c’est d’aimer la vie et de regarder la mort d’un regard tranquille. - Jules Michelet',
  "La beauté commence au moment où vous décidez d'être vous-même. - Coco Chanel",
  "La vie est un mystère qu'il faut vivre et non un problème à résoudre. - Gandhi",
  "Rien n'est permanent, sauf le changement. - Bouddha",
  'Le seul vrai langage au monde est un baiser. - Alfred de Musset',
  'La musique est la langue des émotions. - Emmanuel Kant',
  "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux. - Antoine de Saint-Exupéry",
  "Le bonheur est parfois caché dans l'inconnu. - Victor Hugo",
  "Il y a des moments où il faut choisir entre vivre sa propre vie pleinement, entièrement, complètement, ou traîner l'existence dégradante, creuse et fausse que le monde, dans sa stupidité, nous impose. - Oscar Wilde",
  'La seule façon d’être vraiment satisfait est de faire ce que vous croyez être un excellent travail. - Steve Jobs',
  'La connaissance parle, mais la sagesse écoute. - Jimi Hendrix',
  "On n'est jamais mieux servi que par soi-même. - Proverbe français",
  'La confiance en soi est le premier secret du succès. - Ralph Waldo Emerson',
  "Le pessimiste se plaint du vent, l'optimiste espère qu'il va changer, le réaliste ajuste ses voiles. - William Arthur Ward",
  "La perfection n'est pas atteinte lorsque vous ne pouvez plus rien ajouter, mais lorsque vous ne pouvez plus rien retirer. - Antoine de Saint-Exupéry",
  "La créativité est l'intelligence qui s'amuse. - Albert Einstein",
  'La véritable éducation consiste à tirer le meilleur de soi-même. - Mahatma Gandhi',
  'La patience est amère, mais son fruit est doux. - Jean-Jacques Rousseau',
  "L'optimisme est la foi qui mène à la réalisation. Rien ne peut être fait sans espoir et confiance. - Helen Keller",
  'La simplicité est la sophistication suprême. - Léonard de Vinci',
  'La patience est la clé du soulagement.',
  'Celui qui veut bien vivre doit agir sagement.',
  'La patience est un arbre dont la racine est amère, mais dont les fruits sont doux.',
  'Si tu veux être respecté, respecte-toi toi-même.',
  'La peur d’un danger est souvent plus terrible que le danger lui-même.',
  'Le diable est sage, mais pas autant qu’un homme de bien.',
  'Le chameau ne voit pas sa propre bosse, mais voit celle des autres.',
  "Même la lune ne brille pas autant que l'humilité.",
  'La fortune sourit à celui qui travaille dur.',
  "L'intelligence s'acquiert dans la sérénité et le silence.",
  'Il n’y a pas de honte à apprendre, même auprès de son ennemi.',
  "Celui qui a beaucoup parlé a beaucoup commis d'erreurs.",
  'Le silence est la meilleure réponse à un imbécile.',
  'Un homme n’est pas bon ou mauvais à cause des richesses qu’il possède, mais par ses actes.',
  'Le bienfait du coeur est une source inépuisable de richesse.',
  'Un moment de patience dans un moment de colère évite un siècle de chagrin.',
  "Il vaut mieux une goutte de sagesse qu'un tonneau de science.",
  'La gentillesse est un langage que les sourds peuvent entendre et que les aveugles peuvent voir.',
  'Celui qui se respecte lui-même est respecté par les autres.',
  'Un homme sans patience est comme une lampe sans huile.',
  'Le calme est une force intérieure.',
];
